zfile:
  debug: false
  directLinkPrefix: directlink
  log:
    path: ${user.home}/.zfile/logs
  db:
    path: ${user.home}/.zfile/db/zfile
  tmp:
    path: ${user.home}/.zfile/tmp
  cache:
    auto-refresh:
      interval: 1
    timeout: 1800
  constant:
    readme: readme.md
    password: QAQ
  preview:
    audio:
      maxFileSizeMb: 15
    text:
      maxFileSizeKb: 512
  onedrive:
    clientId: 09939809-c617-43c8-a220-a93c1513c5d4
    clientSecret: _l:zI-_yrW75lV8M61K@z.I2K@B/On6Q
    redirectUri: https://file.qwq.ro/onedrive/callback
    scope: offline_access User.Read Files.ReadWrite.All
  onedrive-china:
    clientId: 4a72d927-1907-488d-9eb2-1b465c53c1c5
    clientSecret: Y9CEA=82da5n-y_]KAWAgLH3?R9xf7Uw
    redirectUri: https://file.qwq.ro/onedrive/china-callback
    scope: offline_access User.Read Files.ReadWrite.All

server:
  port: 7070
  servlet:
    context-path: ''
  tomcat:
    threads:
      max: 20
  compression:
    enabled: true

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: ${zfile.debug}
  datasource:
#    # h2 内存数据库 配置
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:${zfile.db.path}
#    username: zfile
#    password: 123456

    # MySQL 配置
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.1.199:3306/zfile_test?useSSL=true&verifyServerCertificate=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
#      username: root
#      password: Rebind1234*
      url: jdbc:mysql://127.0.0.1:3306/zfile?useSSL=true&verifyServerCertificate=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
      username: zfile
      password: TrKnM2X8fT7NzKCG
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    generate-ddl: true
    defer-datasource-initialization: true
  profiles:
    active: prod

  # 初始化数据导入
  sql:
    init:
      continue-on-error: true
      mode: always
      data-locations: classpath*:db/data.sql
      encoding: utf-8
